# 数据集路径
train: C:\\Users\\Lenovo\\Desktop\\yolov8\\dataset\\train
val: C:\\Users\\Lenovo\\Desktop\\yolov8\\dataset\\valid

# 类别数量
nc: 9

# 类别
names:
  0: one
  1: two
  2: three
  3: four
  4: five
  5: six
  6: seven
  7: eight
  8: nine





